---
- name: Install Redis Server
  apt: name=redis-server state=latest

- name: Install Redis Tools
  apt: name=redis-tools state=latest

- name: Ensure Redis Server is running
  service: name=redis-server state=started enabled=yes