- name: Check if certificate already exists.
  stat:
    path: /etc/letsencrypt/live/{{ domain | replace('*.', '') }}/cert.pem
  register: letsencrypt_cert

- name: Get certificate
  command: "{{ certbot_dir }}/certbot-auto certonly --non-interactive --quiet --agree-tos --email {{ certbot_email }} --standalone -d {{ domain }} {{ certbot_flags }}"
  when: not letsencrypt_cert.stat.exists
  notify: restart nginx